image: docker:latest

services:
    - docker:dind

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  image: ruby:2.4.2
  script:
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker build -t ${DOCKER_LOGIN}/reddit-gitlab:${CI_COMMIT_SHORT_SHA} ./reddit
    - docker push ${DOCKER_LOGIN}/reddit-gitlab:${CI_COMMIT_SHORT_SHA}

test_unit_job:
  stage: test
  image: ruby:2.4.2
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
