version: '3.3'
services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    extra_hosts:
      - 'dockerhost:172.17.0.1'
    networks:
      - back_net
      - front_net
      - monitoring

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongodb_exporter:
    image: bitnami/mongodb-exporter:${VER_MONGODB_EXPORTER}
    environment:
      - MONGODB_URI=mongodb://comment_db:27017
    networks:
      - back_net

  blackbox_exporter:
    image: prom/blackbox-exporter:${VER_BB_EXPORTER}
    container_name: blackbox-exporter
    networks:
      - back_net
      - front_net

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitoring

  telegraf:
    image: ${USER_NAME}/telegraf
    ports:
      - '9273:9273'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - front_net
      - back_net


volumes:
  prometheus_data:
  grafana_data:

networks:
  front_net:
  back_net:
  monitoring:
