version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${HOST_PORT:-9292}:${APP_PORT:-9292}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${VER_POST}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongodb_exporter:
    image: bitnami/mongodb-exporter:${VER_MONGODB_EXPORTER}
    environment:
      - MONGODB_URI=mongodb://comment_db:27017
    networks:
      - back_net

  blackbox_exporter:
    image: prom/blackbox-exporter:${VER_BB_EXPORTER}
    container_name: blackbox-exporter
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
