version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${HOST_PORT:-9292}:${APP_PORT:-9292}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${VER_POST}
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      - front_net
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
